apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: ./ca.crt
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: homework
    user: cd-user
  name: cd-context
current-context: cd-context
users:
- name: cd-user
  user:
    tokenFile: ./token