apiVersion: v1
kind: Service
metadata:
  namespace: homework
  name: homework-service
spec:
  type: ClusterIP
  selector:
    app: homework
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000